# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: meyjan/simple-app:v2
        ports:
          - containerPort: 3000
