# Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: simpleappservice
spec:
  selector:
    app: simpleapp
  ports:
    - protocol: "TCP"
      # From inside
      port: 3001
      # From outside
      nodePort: 30001

      # Target port inside kube
      targetPort: 3000
  type: LoadBalancer

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: meyjan/simple-app:v2
        ports:
          - containerPort: 3000
